//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abbasov_pr7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int Id { get; set; }
        public int GameId { get; set; }
        public int ClientNumber { get; set; }
        public string PartName { get; set; }
        public int Amount { get; set; }
        public string Status { get; set; }
        public System.DateTime TransactionDate { get; set; }
    
        public virtual GameSessions GameSessions { get; set; }
    }
}
